### ISSUE TITLE
> 4x speed increase

### ISSUE THREAD

**Issue by seanrb** [maestro-rayo/levitt-estimate#1]
Hello,

You can get greater than 4x speed increase if you vectorize some of your loops.

For example on lines:
https://github.com/maestro-rayo/levitt-estimate/blob/9592e4700fce312ad4188eac1b27326851556ec1/LevittEstimate.py#L53-L55

This can be re-written in 2 vectorized lines.

First take your conditional `if > 0` and apply it all at once.  This should be done outside the `for N` loop as it doesn't change:
```valid_data = data[data > 0]```

Now you can use this and apply the math all at once:
```y = -np.log(np.log(N) - np.log(valid_data.values))```

Code should look something like:
```python
valid_data = data[data > 0]
coeff = []
for N in range(max(data)+1,max(data) + max_search):
    y = -np.log(np.log(N) - np.log(valid_data.values))
```

Testing on my computer it had almost 5x speed increase.

Here is the original timing ~20ms.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/48166471/92840293-09052e80-f435-11ea-90d5-1a7017d8c1d2.png">

Here is the new timing ~4ms.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/48166471/92840393-220ddf80-f435-11ea-932e-b7501fc537e3.png">

FYI here is a good article that talks about how to optimize Python for speed using Pandas/numpy vectors: https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6

**Comment by maestro-rayo** [comment]
Thanks!

**Comment by maestro-rayo** [comment]
I have pushed a version including your suggestion and some other minor changes.
